### PR TITLE
Replace Travis with GH CI

### PR DESCRIPTION
**Pull request by urschrei**

### CODE REVIEW

**Comment by urschrei** [comment]
Will this work? Who can say?

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
@frewsxcv Are you an existing reviewer?

**Comment by frewsxcv** [comment]
@urschrei Just made you a reviewer. Can you try again?

**Comment by urschrei** [comment]
Bors try

**Comment by urschrei** [comment]
Bors r+

**Pull request merged**
